name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows-cpu:
    runs-on: windows-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: x64
        cache: pip
    - name: Installing build dependencies
      run: python -m pip install --upgrade pip wheel setuptools pyinstaller
    - name: Installing project dependencies
      run: |
        cd server
        python -m pip install -r requirements-common.txt -r requirements-dml.txt
    - name: Building executable
      run: pyinstaller --clean -y --dist ./dist --workpath /tmp MMVCServerSIO.spec
    - name: Uploading artifact
      uses: actions/upload-artifact@v4
      with:
        name: voice-changer
        path: server/dist

  # linux-cpu:
    # runs-on: ubuntu-latest
    # steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: '3.10'
    #     architecture: 'x64'
    #     cache: 'pip'
    # - name: Installing build dependencies
    #   run: python -m pip install --upgrade pip wheel setuptools pyinstaller
    # - name: Installing project dependencies
    #   run: |
    #     cd server
    #     python -m pip install -r requirements-common.txt -r requirements-dml.txt
    # - name: Building executable
    #   run: pyinstaller --clean -y --dist ./dist --workpath /tmp MMVCServerSIO.spec
    # - name: Uploading artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: voice-changer
    #     path: server/dist