name: Package exe with PyInstaller

on:
  push:
    branches: [ master-custom ]
  pull_request:
    branches: [ master-custom ]


jobs:
  build-all:
    strategy:
      matrix:
        include:
        - os: windows-latest
          os_suffix: windows-amd64
          backend: cuda
        - os: windows-latest
          os_suffix: windows-amd64
          backend: dml
        - os: macos-latest
          os_suffix: macos-amd64
          backend: cpu
        - os: ubuntu-latest
          os_suffix: linux-amd64
          backend: cpu
        - os: ubuntu-latest
          os_suffix: linux-amd64
          backend: cuda
        # - os: ubuntu-latest
        #   os_suffix: linux-amd64
        #   backend: rocm
    runs-on: ${{ matrix.os }}
    env:
      BACKEND: ${{ matrix.backend }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
        # cache: pip
    - name: Installing build dependencies
      run: python -m pip install --upgrade pip wheel setuptools pyinstaller
    - name: Installing project dependencies
      run: python -m pip install -r requirements-common.txt -r requirements-${{ matrix.backend }}.txt
      working-directory: ./server
    - name: Building executable
      run: pyinstaller --clean -y --dist ./dist --workpath /tmp MMVCServerSIO.spec
      working-directory: ./server
    - name: Uploading artifact
      uses: actions/upload-artifact@v4
      with:
        name: voice-changer-${{ matrix.os_suffix }}-${{ matrix.backend }}
        path: ./server/dist

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master-custom' }}

    runs-on: ubuntu-latest

    needs:
    - build-all

    steps:
    - name: Clone
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        BUILD_NUMBER="$(git rev-list --count HEAD)"
        SHORT_HASH="$(git rev-parse --short=7 HEAD)"
        if [[ "${{ env.BRANCH_NAME }}" == "master" ]]; then
          echo "name=b${BUILD_NUMBER}" >> $GITHUB_OUTPUT
        else
          SAFE_NAME=$(echo "${{ env.BRANCH_NAME }}" | tr '/' '-')
          echo "name=${SAFE_NAME}-b${BUILD_NUMBER}-${SHORT_HASH}" >> $GITHUB_OUTPUT
        fi

    - name: Download artifacts
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        path: ./artifact

    - name: Move artifacts
      id: move_artifacts
      run: mkdir -p ./artifact/release && mv ./artifact/*/*.zip ./artifact/release

    - name: Create release
      id: create_release
      uses: anzz1/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.name }}

    - name: Upload release
      id: upload_release
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const path = require('path');
          const fs = require('fs');
          const release_id = '${{ steps.create_release.outputs.id }}';
          for (let file of await fs.readdirSync('./artifact/release')) {
            if (path.extname(file) === '.zip') {
              console.log('uploadReleaseAsset', file);
              await github.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release_id,
                name: file,
                data: await fs.readFileSync(`./artifact/release/${file}`)
              });
            }
          }
